### ISSUE TITLE
AttributeError: '_module_functionBackward' object has no attribute 'set_materialize_grads'

### ISSUE THREAD

**Issue by Tara8573** [USTC3DV/NeRFBlendShape-code#19]
Thank you for your wonderful work!!!

When I run the inference code, I encountered the following problems. Could you give me some suggestions? Thank you so much！
（Environment: Ubuntu 18.04, 2080Ti, cuda 10.2, pytorch 1.6.0,  python3.8, gcc 8.1.0, cmake 3.21）
```
  File "....../NeRFBlendShape/nerf/network_tcnn.py", line 127, in forward
    h = self.sigma_net(x)
  File "....../lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "....../lib/python3.8/site-packages/tinycudann-1.7-py3.8-linux-x86_64.egg/tinycudann/modules.py", line 177, in forward
    output = _module_function.apply(
  File "....../lib/python3.8/site-packages/tinycudann-1.7-py3.8-linux-x86_64.egg/tinycudann/modules.py", line 87, in forward
    ctx.set_materialize_grads(False)
AttributeError: '_module_functionBackward' object has no attribute 'set_materialize_grads'
```

**Comment by XuanGhahahaha** [comment]
Hi, thanks for your interest in our work.

It seems that this error originate from the backward function in tcnn. Maybe this [issue](https://github.com/NVlabs/tiny-cuda-nn/issues/84) could help you. You could try updating your torch or use a older version tcnn.

**Comment by Tara8573** [comment]
Thanks!!!!It works fine with tinycudann 1.4.
